version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
      day: "sunday"
    assignees:
      - "octocat"
      - "prasadtalasila"
    commit-message:
      prefix: "client-npm: "
    target-branch: "dependabot-merge"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "npm"
    directory: "/servers/lib"
    schedule:
      interval: "weekly"
      day: "sunday"
    assignees:
      - "octocat"
      - "prasadtalasila"
    commit-message:
      prefix: "libms-npm: "
    target-branch: "dependabot-merge"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "npm"
    directory: "/servers/execution/runner"
    schedule:
      interval: "weekly"
      day: "sunday"
    assignees:
      - "octocat"
      - "prasadtalasila"
    commit-message:
      prefix: "runner-npm: "
    target-branch: "dependabot-merge"
    pull-request-branch-name:
      separator: "-"
