# Reusable workflow for building and pushing a Docker Image to DockerHub.
# 
# Auth username is taken from the repository secret, "DOCKERHUB_USERNAME"
# Publish username is taken from the repository secret, "DOCKERHUB_SCOPE"
# Password is taken from the repository secret, "DOCKERHUB_TOKEN"
# 
# NOTE: DockerHub currently does not provide PATs for organizations.
# Users belonging to the org must use their own, which is why we need a
# username to publish through: DOCKERHUB_USERNAME, and a username to publish
# under: DOCKERHUB_SCOPE.
# You may use the same username for both.

name: Build and Push Docker Image (DockerHub)

permissions:
  contents: read  # ✅ Required for checking out the code
  packages: write  # ✅ Push to github package registry

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      version:
        required: true
        type: string
        default: "latest"
      dockerfile:
        required: true
        type: string
      readme-file:
        required: true
        type: string
    secrets:
      # Username used for DockerHub authorization
      DOCKERHUB_USERNAME:
        required: true
        # Username under which the image will be published
      DOCKERHUB_SCOPE:
        required: true
        # Personal Access Token created by the user `DOCKERHUB_USERNAME`
        # Must have read, write and delete permissions
      DOCKERHUB_TOKEN:
        required: true

env:
  registry: docker.io
  username: ${{ secrets.DOCKERHUB_USERNAME }}
  dockerhub-scope: ${{ secrets.DOCKERHUB_SCOPE }}
  password: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read  # ✅ Required for checking out the code
      packages: write  # ✅ Required for publishing to github package registry

    steps:
      - name: Checkout Repository
        # v6.0.1
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Setup node
        if: ${{ inputs.image-name == 'dtaas-web' }}
        # v6.1.0
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f
        with:
          node-version: 24
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: Build react client website
        if: ${{ inputs.image-name == 'dtaas-web' }}
        run: |
          cd client/
          yarn install --network-timeout 1000000
          yarn build

      - name: Log in to the Container registry
        # v3.6.0
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          registry: ${{ env.registry }}
          username: ${{ env.username }}
          password: ${{ env.password }}

      - name: Check if version exists
        id: check_version
        env:
          IMAGE_TAG: "${{ env.registry }}/${{ env.dockerhub-scope }}/${{ inputs.image-name }}:${{ inputs.version }}"
        run: |
          if docker manifest inspect "$IMAGE_TAG" > /dev/null 2>&1; then
            echo "Version ${{ inputs.version }} already exists."
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "Version ${{ inputs.version }} does not exist."
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        if: env.exists == 'false'
        # v6.18.0
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: .
          file: ./docker/${{ inputs.dockerfile }}
          push: true
          tags: |
            ${{ env.registry }}/${{ env.dockerhub-scope }}/${{ inputs.image-name }}:${{ inputs.version }}
            ${{ env.registry }}/${{ env.dockerhub-scope }}/${{ inputs.image-name }}:latest

      - name: Docker Hub Description
        # v5.0.0
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa
        with:
          username: ${{ env.username }}
          password: ${{ env.password }}
          repository: ${{ env.dockerhub-scope }}/${{ inputs.image-name }}
          readme-filepath: ${{ inputs.readme-file }}
