name: Build documentation

on:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

permissions:
  contents: read # âœ… Required for checking out the code

jobs:
  docs:
    name: Build html docs only
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1

      - name: build docs
        uses: Tiryoh/actions-mkdocs@14d3fd544b7a2bcffcdd86b05d558f20c244c9fc #v0.24.0
        with:
          mkdocs_version: 'latest'
          requirements: 'docs/requirements-github.txt'
          configfile: 'mkdocs-github.yml'


      - name: show contents of compiled docs
        run: |
          ls -R site
