name: Library microservice

on:
  push:
    paths:
      - 'servers/lib/**'
      - '.github/workflows/lib-ms.yml'
  pull_request:
    paths:
      - 'servers/lib/**'
      - '.github/workflows/lib-ms.yml'
  workflow_dispatch:

env:
  NODE_VERSION: 24
  HTTP_PORT: 4002
  LIBMS_CONFIG_PATH: test/libms.test.yaml

jobs:
  test-lib-ms:
    permissions:
      contents: read  # Required for checking out the code
    name: Test library microservice
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: servers/lib

    steps:
      - name: Checkout
        # v6.0.1
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Setup node
        # v6.1.0
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: Install pm2 and jest
        run: |
          npm install -g pm2
          npm install -g jest

      - name: Run the linting checks and formatting
        run: |
          yarn install
          yarn syntax
          yarn format

      - name: Build the lib microservice
        run: |
          yarn build

      - name: Run all tests
        run: |
          yarn build
          yarn test:all

      - name: Upload test coverage to Codecov
        # v5.5.2
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: servers/lib/coverage/clover.xml
          flags: lib-microservice-tests

      - name: Update configuration
        env:
          LIBMS_LOCAL_PATH: ${{ github.workspace }}/files
          LIBMS_PORT: ${{ env.HTTP_PORT }}
        run: |
          node test/update-config.js

      - name: Start http mode
        env:
          LIBMS_CONFIG_PATH: ${{ env.LIBMS_CONFIG_PATH }}
        run: |
          yarn build
          yarn start:pm2

      - name: Check server is running (Windows)
        if: runner.os == 'Windows'
        env:
          PORT: ${{ env.HTTP_PORT }}
        # v3.0.2
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08
        with:
          timeout_seconds: 10
          max_attempts: 4
          command: |
            Invoke-WebRequest `
              -Uri http://localhost:${{ env.PORT }}/lib/files `
              -Method Head `
              -UseBasicParsing

      - name: Check server is running (Linux)
        if: runner.os != 'Windows'
        env:
          PORT: ${{ env.HTTP_PORT }}
        # v3.0.2
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08
        with:
          timeout_seconds: 10
          max_attempts: 4
          command: "curl -f -LI http://localhost:${{ env.PORT }}/lib/files"

      - name: Run http test
        env:
          PORT: ${{ env.HTTP_PORT }}
          LOCAL_PATH: ${{ github.workspace }}/files
          MODE: local
          LOG_LEVEL: debug
          APOLLO_PATH: /lib
        run: |
          yarn test:http-github

      - name: Stop http mode
        run: |
          yarn stop:pm2

  get-version:
    permissions:
      contents: read  # Required for checking out the code
    name: Get version and variables
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        # v6.0.1
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - name: Install jq
        run: sudo apt-get install -y jq
      - name: get version
        id: get-version
        run: | 
          version=$(jq -r '.version' ./servers/lib/package.json)
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "node-version=$NODE_VERSION" >> $GITHUB_OUTPUT
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      node-version: ${{ steps.get-version.outputs.node-version }}

  publish-package-github:
    permissions:
      contents: read  # Required for checking out the code
      packages: write  # Required for github package registry
    if: |
      github.event_name == 'push' &&
      (
        startsWith(github.ref, 'refs/heads/feature/') ||
        startsWith(github.ref, 'refs/heads/release-v')
      )

    name: Publish to GitHub Packages
    needs: [get-version, test-lib-ms]
    uses: ./.github/workflows/publish-npm.yml
    with:
      node-version: ${{ needs.get-version.outputs.node-version }}
      registry-url: 'https://npm.pkg.github.com/'
      directory: servers/lib
      package-name: ${{ vars.PACKAGE_NAME || '' }}
    secrets:
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-package-npm:
    permissions:
      packages: write  # Push to github package registry
      contents: read  # Required for checking out the code
    if: |
      github.event_name == 'push' &&
      (
        startsWith(github.ref, 'refs/heads/feature/') ||
        startsWith(github.ref, 'refs/heads/release-v')
      )

    name: Publish to NPM
    needs: [get-version, test-lib-ms]
    uses: ./.github/workflows/publish-npm.yml
    with:
      node-version: ${{ needs.get-version.outputs.node-version }}
      registry-url: 'https://registry.npmjs.org'
      directory: servers/lib
      package-name: ${{ vars.PACKAGE_NAME || '' }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-docker-image-ghcr:
    permissions:
      contents: read  # Required for checking out the code
      packages: write  # Required for publishing to github package registry
    if: |
      github.event_name == 'push' &&
      (
        startsWith(github.ref, 'refs/heads/feature/') ||
        startsWith(github.ref, 'refs/heads/release-v')
      )

    name: Publish Docker image (GHCR)
    needs: [get-version, test-lib-ms]
    uses: ./.github/workflows/docker-ghcr.yml
    with:
      image-name: libms
      version: ${{ needs.get-version.outputs.version }}
      dockerfile: libms.dockerfile
    secrets: inherit

  publish-docker-image-dockerhub:
    permissions:
      contents: read  # Required for checking out the code
      packages: write  # Required for publishing to github package registry
    if: |
      github.event_name == 'push' &&
      (
        startsWith(github.ref, 'refs/heads/feature/') ||
        startsWith(github.ref, 'refs/heads/release-v')
      )

    name: Publish Docker image (DockerHub)
    needs: [get-version, test-lib-ms]
    uses: ./.github/workflows/docker-dockerhub.yml
    with:
      image-name: libms
      version: ${{ needs.get-version.outputs.version }}
      dockerfile: libms.dockerfile
      readme-file: servers/lib/DOCKER.md
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_SCOPE: ${{ secrets.DOCKERHUB_SCOPE }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
