name: Digital twin runner

on:
  push:
    paths:
      - 'servers/execution/**'
      - '.github/workflows/runner.yml'
  pull_request:
    paths:
      - 'servers/execution/**'
      - '.github/workflows/runner.yml'
  workflow_dispatch:

env:
  NODE_VERSION: 24

permissions:
  contents: read  # ✅ Required for checking out the code
  packages: write  # ✅ Push to github package registry

jobs:
  test-runner:
    permissions:
      contents: read  # ✅ Required for checking out the code
    name: Test digital twin runner
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: servers/execution/runner/

    steps:
      - name: Checkout
        # v6.0.1
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Setup node
        # v6.1.0
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f
        with:
          node-version: 24
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: Run linting and formatting checks on runner
        run: |
          npm install -g prettier
          yarn install
          yarn syntax
          prettier -c --ignore-path ../.gitignore "**/*.{ts,tsx,css,scss}"

      - name: Build the runner
        if: success() || failure()
        run: |
          yarn build

      - name: Run tests
        if: success() || failure()
        run: |
          yarn test

      - name: Upload test coverage to Codecov
        # v5.5.2
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: servers/execution/runner/coverage/clover.xml
          flags: dt-runner

  get-version:
    permissions:
      contents: read  # ✅ Required for checking out the code
    name: Get version and variables
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
          # v6.0.1
          uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        - name: Install jq
          run: sudo apt-get install -y jq
        - name: get version
          id: get-version
          run: | 
            version=$(jq -r '.version' ./servers/execution/runner/package.json)
            echo "version=$version" >> $GITHUB_OUTPUT
            echo "node-version=$NODE_VERSION" >> $GITHUB_OUTPUT
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      node-version: ${{ steps.get-version.outputs.node-version }}

  publish-package-github:
    permissions:
      contents: read  # ✅ Required for checking out the code
      packages: write  # ✅ Push to github package registry

    if: | 
      github.event_name == 'push' &&
      (
        startsWith(github.ref, 'refs/heads/feature/') ||
        startsWith(github.ref, 'refs/heads/release-v')
      )

    name: Publish to GitHub Packages
    needs: [test-runner, get-version]
    uses: ./.github/workflows/publish-npm.yml
    with:
      node-version: ${{ needs.get-version.outputs.node-version }}
      registry-url: 'https://npm.pkg.github.com/'
      directory: servers/execution/runner
      package-name: ${{ vars.NPM_RUNNER_PACKAGE_NAME || '' }}
    secrets:
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-package-npm:
    permissions:
      contents: read  # ✅ Required for checking out the code
      packages: write  # ✅ Push to github package registry
    if: | 
      github.event_name == 'push' &&
      (
        startsWith(github.ref, 'refs/heads/feature/') ||
        startsWith(github.ref, 'refs/heads/release-v')
      )

    name: Publish to NPM
    needs: [get-version, test-runner]
    uses: ./.github/workflows/publish-npm.yml
    with:
      node-version: ${{ needs.get-version.outputs.node-version }}
      registry-url: 'https://registry.npmjs.org'
      directory: servers/execution/runner
      package-name: ${{ vars.NPM_RUNNER_PACKAGE_NAME || '' }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
